# Generated by Django 2.0.6 on 2019-05-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btable',
            options={},
        ),
    ]
