# Generated by Django 2.0.6 on 2019-05-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20190518_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btable',
            options={'managed': False},
        ),
    ]
